<?php
/**
 * RapidCampaign
 *
 * @category    RapidCampaign
 * @package     RapidCampaign_Promotions
 * @copyright   Copyright (c) 2015 RapidCampaign (http://rapidcampaign.com)
 */
?>
<?php $_element = $this->getElement() ?>
<div class="rule-tree">
    <fieldset id="<?php echo $_element->getHtmlId() ?>" <?php echo $_element->serialize(array('class')) ?>>
    <?php if ($_element->getComment()): ?>
        <p class="comment"><?php echo $this->escapeHtml($_element->getComment()) ?></p>
    <?php endif; ?>
    <?php echo $_element->getChildrenHtml() ?>
    </fieldset>
</div>
<script type="text/javascript">
    (function() {
        var rulesForm = document.createElement('script');
        rulesForm.type = 'text/javascript';
        var rulesFormInnerHtml = "var <?php echo $_element->getHtmlId() ?> = new VarienRulesForm('<?php echo $_element->getHtmlId() ?>', '<?php echo $this->getNewChildUrl() ?>');";

        <?php if ($_element->getReadonly()): ?>
        rulesFormInnerHtml += "<?php echo $_element->getHtmlId() ?>.setReadonly(true);";
        <?php endif; ?>

        rulesForm.innerHTML = rulesFormInnerHtml;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(rulesForm, s);
    })();
</script>